### ISSUE TITLE
i3 polybar module memory leaks

### ISSUE THREAD

**Issue by Burlter** [resloved/i3#10]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
This happens when i select workspaces or just exep polybar 
```
=================================================================
==1751==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 34 byte(s) in 1 object(s) allocated from:
#0 0x7f4000186248 in __interceptor_malloc (/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/libasan.so.5+0x10c248)
#1 0x7f3fff94175f (/lib64/libc.so.6+0x7d75f)

SUMMARY: AddressSanitizer: 34 byte(s) leaked in 1 allocation(s).

=================================================================
==1753==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 34 byte(s) in 1 object(s) allocated from:
#0 0x7f4bab1cf248 in __interceptor_malloc (/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/libasan.so.5+0x10c248)
#1 0x7f4baa98a75f (/lib64/libc.so.6+0x7d75f)

SUMMARY: AddressSanitizer: 34 byte(s) leaked in 1 allocation(s).
warn: The config parameter `module/xkeyboard.label-indicator` is deprecated, use `module/xkeyboard.label-indicator-on` instead.

=================================================================
==1759==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 34 byte(s) in 1 object(s) allocated from:
#0 0x7fd49d12c248 in __interceptor_malloc (/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/libasan.so.5+0x10c248)
#1 0x7fd49c8e775f (/lib64/libc.so.6+0x7d75f)

SUMMARY: AddressSanitizer: 34 byte(s) leaked in 1 allocation(s).
```

## Reproduction Instructions
Select i3 module with config from [polybar manual](https://github.com/polybar/polybar/wiki/Module:-i3). And yes, i rebuild both polybar and i3, but error still popup. After i install normal i3-gaps, errors are gone. 

## Environment
Use this i3 [ebuild](https://github.com/resloved/i3/files/4239658/i3-rounded-9999.txt) 

<pre>
- Linux Distribution & Version:  gentoo 17, gentoo-kernel 4.19.97
- I am using compton compositor
</pre>

**Comment by resloved** [comment]
I don't know what change I could have made that would cause this, but it might be an issue with old i3-gaps as I haven't kept up with the changes. I've been meaning to merge the upstream changes and this is probably a good enough excuse to give it a go.

**Comment by resloved** [comment]
@Burlter Can you trying building the [shape-merge](https://github.com/resloved/i3/tree/shape-merge) branch? It includes a bunch of changes from upstream i3-gaps and might fix your issue. If not at least it narrows down what the problem could be.

**Comment by Burlter** [comment]
I build shape-merge branch, but it does not help.

**Comment by resloved** [comment]
Hmm, guess I'll have to try and reproduce it then

**Comment by blurm** [comment]
Does It have noticeable influence on long time running performance?

**Comment by Burlter** [comment]
It seems that not your problem. In i3-gaps build adress sanitaizer just turned off
