### ISSUE TITLE
Use https for GitHub in PGKBUILD in AUR

### ISSUE THREAD

**Issue by rubenhorn** [resloved/i3#22]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
Cannot download code when installing through AUR (blocked by GitHub).

## Solution
Use `git+https://` instead of `git://` in [this line](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=i3-gaps-rounded-git#n24).

**Comment by resloved** [comment]
I haven't looked into this at all, but if there is an issue with the AUR package it isn't managed by me. Looks like you'd have to talk to [rhysperry111](https://aur.archlinux.org/account/rhysperry111).
