### ISSUE TITLE
Setting border_radius 0 doesn't make corners square

### ISSUE THREAD

**Issue by brandoncazander** [resloved/i3#8]
Setting `border_radius 0` acts the same as setting `border_radius 4`. It looks to be caused by [this change](https://github.com/resloved/i3/pull/3/commits/098c69ec075833597b42891ddbf668f64429d072#diff-48a77dc8e807a60a46ad9d347bea3e6cR544).

My use case is that sometimes I don't want my corners to be rounded.

**Comment by resloved** [comment]
I'm not able to replicate, setting border_radius to 0 works as intended on the latest changes.

![No Corner](https://i.imgur.com/JfebTkL.png)

The changes you are looking at were from the original pull request from AlisCode, but I actually requested for that default to be removed. So you might just be using an out of date version or there is another problem entirely.

You can check the [source code](https://github.com/resloved/i3/blob/shape/src/x.c#L482) if you don't believe me.

**Comment by brandoncazander** [comment]
I didn't believe you until I read the source code. I was mistaken. Please accept my apologies and ban me from the issue tracker, thanks!
